-- Seed teams required by existing report assignments before adding the FK.
-- Safe to run multiple times.

begin;

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.teams
  add column if not exists name text,
  add column if not exists description text,
  add column if not exists is_active boolean not null default true;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'teams_name_key'
  ) then
    alter table public.teams
      add constraint teams_name_key unique (name);
  end if;
end
$$;

insert into public.teams (name, description, is_active)
values
  ('Line Crew A', 'Default line response team.', true),
  ('Line Crew B', 'Secondary line response team.', true),
  ('Maintenance', 'Maintenance response team.', true),
  ('Inspection', 'Inspection and validation team.', true)
on conflict (name) do update
set
  is_active = excluded.is_active,
  description = coalesce(public.teams.description, excluded.description);

alter table public.reports
  add column if not exists assigned_team text;

update public.reports
set assigned_team = nullif(btrim(assigned_team), '')
where assigned_team is distinct from nullif(btrim(assigned_team), '');

insert into public.teams (name, is_active)
select distinct nullif(btrim(assigned_team), ''), true
from public.reports
where nullif(btrim(assigned_team), '') is not null
on conflict (name) do update
set is_active = excluded.is_active;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'reports_assigned_team_fkey'
  ) then
    alter table public.reports
      add constraint reports_assigned_team_fkey
      foreign key (assigned_team) references public.teams(name)
      on update cascade
      on delete set null;
  end if;
end
$$;

commit;
