-- Restore missing team snapshot compatibility objects used by report submit
-- and assignment flows. Safe to run multiple times.

begin;

alter table public.reports
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.assigned_team_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.assigned_team_snapshots
  add column if not exists report_id bigint,
  add column if not exists report_created_at timestamptz,
  add column if not exists snapshot_at timestamptz not null default now(),
  add column if not exists captured_at timestamptz,
  add column if not exists queue_number bigint,
  add column if not exists assigned_team text,
  add column if not exists team_name text,
  add column if not exists status text,
  add column if not exists municipality text,
  add column if not exists barangay text,
  add column if not exists location_text text,
  add column if not exists issue_type text,
  add column if not exists description text,
  add column if not exists latitude float8,
  add column if not exists longitude float8,
  add column if not exists source text,
  add column if not exists full_name text,
  add column if not exists contact text,
  add column if not exists is_urgent boolean not null default false,
  add column if not exists resolved_at timestamptz,
  add column if not exists remarks text;

create index if not exists assigned_team_snapshots_report_id_idx
  on public.assigned_team_snapshots (report_id);

create index if not exists assigned_team_snapshots_assigned_team_idx
  on public.assigned_team_snapshots (assigned_team);

create index if not exists assigned_team_snapshots_team_name_idx
  on public.assigned_team_snapshots (team_name);

create index if not exists assigned_team_snapshots_snapshot_at_idx
  on public.assigned_team_snapshots (snapshot_at desc);

with report_id_ranked as (
  select
    id,
    row_number() over (
      partition by report_id
      order by coalesce(snapshot_at, updated_at, created_at) desc, id desc
    ) as rn
  from public.assigned_team_snapshots
  where report_id is not null
)
delete from public.assigned_team_snapshots s
using report_id_ranked r
where s.id = r.id
  and r.rn > 1;

with queue_number_ranked as (
  select
    id,
    row_number() over (
      partition by queue_number
      order by coalesce(snapshot_at, updated_at, created_at) desc, id desc
    ) as rn
  from public.assigned_team_snapshots
  where queue_number is not null
)
delete from public.assigned_team_snapshots s
using queue_number_ranked q
where s.id = q.id
  and q.rn > 1;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'assigned_team_snapshots_report_id_fkey'
  ) then
    alter table public.assigned_team_snapshots
      add constraint assigned_team_snapshots_report_id_fkey
      foreign key (report_id) references public.reports(id) on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'assigned_team_snapshots_report_id_key'
  ) then
    alter table public.assigned_team_snapshots
      add constraint assigned_team_snapshots_report_id_key unique (report_id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'assigned_team_snapshots_queue_number_key'
  ) then
    alter table public.assigned_team_snapshots
      add constraint assigned_team_snapshots_queue_number_key unique (queue_number);
  end if;
end
$$;

create or replace function public.sync_assigned_team_snapshot_team_fields()
returns trigger
language plpgsql
as $$
begin
  if nullif(btrim(coalesce(new.assigned_team, '')), '') is null then
    new.assigned_team := nullif(btrim(coalesce(new.team_name, '')), '');
  end if;
  if nullif(btrim(coalesce(new.team_name, '')), '') is null then
    new.team_name := nullif(btrim(coalesce(new.assigned_team, '')), '');
  end if;
  return new;
end;
$$;

drop trigger if exists sync_assigned_team_snapshot_team_fields
on public.assigned_team_snapshots;

create trigger sync_assigned_team_snapshot_team_fields
before insert or update on public.assigned_team_snapshots
for each row
execute function public.sync_assigned_team_snapshot_team_fields();

commit;
