-- Customer registration and login support for browser-based auth.
-- Creates a protected customer_users table plus RPC functions for
-- registration and login. Safe to run multiple times.

begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.customer_users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  account_number text,
  contact_number text,
  municipality text,
  barangay text,
  password_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

alter table public.customer_users
  add column if not exists full_name text,
  add column if not exists email text,
  add column if not exists account_number text,
  add column if not exists contact_number text,
  add column if not exists municipality text,
  add column if not exists barangay text,
  add column if not exists password_hash text,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists last_login_at timestamptz;

create unique index if not exists customer_users_email_unique_idx
  on public.customer_users (lower(email));

create unique index if not exists customer_users_account_number_unique_idx
  on public.customer_users (account_number)
  where nullif(btrim(account_number), '') is not null;

alter table public.customer_users enable row level security;

revoke all on public.customer_users from anon, authenticated;

create or replace function public.touch_customer_users_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_customer_users_updated_at on public.customer_users;

create trigger set_customer_users_updated_at
before update on public.customer_users
for each row
execute function public.touch_customer_users_updated_at();

create or replace function public.register_customer_user(
  p_full_name text,
  p_email text,
  p_password text,
  p_account_number text default null,
  p_contact_number text default null,
  p_municipality text default null,
  p_barangay text default null
)
returns table (
  id bigint,
  full_name text,
  email text,
  account_number text,
  contact_number text,
  municipality text,
  barangay text,
  created_at timestamptz,
  last_login_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_account_number text := nullif(btrim(coalesce(p_account_number, '')), '');
  v_contact_number text := nullif(btrim(coalesce(p_contact_number, '')), '');
  v_municipality text := nullif(btrim(coalesce(p_municipality, '')), '');
  v_barangay text := nullif(btrim(coalesce(p_barangay, '')), '');
begin
  if btrim(coalesce(p_full_name, '')) = '' then
    raise exception 'Full name is required';
  end if;

  if v_email = '' or position('@' in v_email) = 0 then
    raise exception 'Valid email is required';
  end if;

  if length(coalesce(p_password, '')) < 8 then
    raise exception 'Password must be at least 8 characters';
  end if;

  if exists (
    select 1
    from public.customer_users cu
    where lower(cu.email) = v_email
  ) then
    raise exception 'Email is already registered';
  end if;

  if v_account_number is not null and exists (
    select 1
    from public.customer_users cu
    where cu.account_number = v_account_number
  ) then
    raise exception 'Account number is already registered';
  end if;

  return query
  insert into public.customer_users (
    full_name,
    email,
    account_number,
    contact_number,
    municipality,
    barangay,
    password_hash
  )
  values (
    btrim(p_full_name),
    v_email,
    v_account_number,
    v_contact_number,
    v_municipality,
    v_barangay,
    extensions.crypt(p_password, extensions.gen_salt('bf', 10))
  )
  returning
    customer_users.id,
    customer_users.full_name,
    customer_users.email,
    customer_users.account_number,
    customer_users.contact_number,
    customer_users.municipality,
    customer_users.barangay,
    customer_users.created_at,
    customer_users.last_login_at;
end;
$$;

create or replace function public.login_customer_user(
  p_email text,
  p_password text
)
returns table (
  id bigint,
  full_name text,
  email text,
  account_number text,
  contact_number text,
  municipality text,
  barangay text,
  created_at timestamptz,
  last_login_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_user public.customer_users%rowtype;
begin
  if v_email = '' or coalesce(p_password, '') = '' then
    raise exception 'Invalid email or password';
  end if;

  select *
  into v_user
  from public.customer_users cu
  where lower(cu.email) = v_email
    and cu.is_active = true
  limit 1;

  if v_user.id is null then
    raise exception 'Invalid email or password';
  end if;

  if v_user.password_hash is null
     or extensions.crypt(p_password, v_user.password_hash) <> v_user.password_hash then
    raise exception 'Invalid email or password';
  end if;

  update public.customer_users
  set last_login_at = now()
  where customer_users.id = v_user.id
  returning *
  into v_user;

  return query
  select
    v_user.id,
    v_user.full_name,
    v_user.email,
    v_user.account_number,
    v_user.contact_number,
    v_user.municipality,
    v_user.barangay,
    v_user.created_at,
    v_user.last_login_at;
end;
$$;

revoke all on function public.register_customer_user(text, text, text, text, text, text, text) from public;
revoke all on function public.login_customer_user(text, text) from public;

grant execute on function public.register_customer_user(text, text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.login_customer_user(text, text) to anon, authenticated;

commit;
