-- Full schema setup for SAMELCO system
-- Includes: customer_users (users), teams, reports, assigned_team_snapshots,
-- report_images, admin_users, notifications, report_status_history
-- Safe to run multiple times (Idempotent)

BEGIN;

-- 1. Enable pgcrypto for password hashing
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- ==========================================
-- 2. customer_users (User's "users" table)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.customer_users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Ensure all columns exist
ALTER TABLE public.customer_users
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS account_number text,
  ADD COLUMN IF NOT EXISTS contact_number text,
  ADD COLUMN IF NOT EXISTS municipality text,
  ADD COLUMN IF NOT EXISTS barangay text,
  ADD COLUMN IF NOT EXISTS password_hash text,
  ADD COLUMN IF NOT EXISTS is_active boolean not null default true,
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz;

-- Unique constraints
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'customer_users_email_unique_idx') THEN
        CREATE UNIQUE INDEX customer_users_email_unique_idx ON public.customer_users (lower(email));
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'customer_users_account_number_unique_idx') THEN
        CREATE UNIQUE INDEX customer_users_account_number_unique_idx ON public.customer_users (account_number) WHERE nullif(btrim(account_number), '') IS NOT NULL;
    END IF;
END
$$;

-- Enable RLS
ALTER TABLE public.customer_users ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 3. teams
-- ==========================================
CREATE TABLE IF NOT EXISTS public.teams (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

ALTER TABLE public.teams
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS is_active boolean not null default true;

-- Unique constraint on name
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'teams_name_key') THEN
        ALTER TABLE public.teams ADD CONSTRAINT teams_name_key UNIQUE (name);
    END IF;
END
$$;

INSERT INTO public.teams (name, description, is_active)
VALUES
    ('Line Crew A', 'Default line response team.', true),
    ('Line Crew B', 'Secondary line response team.', true),
    ('Maintenance', 'Maintenance response team.', true),
    ('Inspection', 'Inspection and validation team.', true)
ON CONFLICT (name) DO UPDATE
SET
    is_active = EXCLUDED.is_active,
    description = COALESCE(public.teams.description, EXCLUDED.description);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 4. reports
-- ==========================================
CREATE TABLE IF NOT EXISTS public.reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

ALTER TABLE public.reports
  ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS contact text,
  ADD COLUMN IF NOT EXISTS location_text text,
  ADD COLUMN IF NOT EXISTS issue_type text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS latitude float8,
  ADD COLUMN IF NOT EXISTS longitude float8,
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS municipality text,
  ADD COLUMN IF NOT EXISTS barangay text,
  ADD COLUMN IF NOT EXISTS status text not null default 'pending',
  ADD COLUMN IF NOT EXISTS resolved_at timestamptz,
  ADD COLUMN IF NOT EXISTS is_urgent boolean default false,
  ADD COLUMN IF NOT EXISTS queue_number bigint,
  ADD COLUMN IF NOT EXISTS assigned_team text;

UPDATE public.reports
SET assigned_team = nullif(btrim(assigned_team), '')
WHERE assigned_team IS DISTINCT FROM nullif(btrim(assigned_team), '');

INSERT INTO public.teams (name, is_active)
SELECT DISTINCT nullif(btrim(assigned_team), ''), true
FROM public.reports
WHERE nullif(btrim(assigned_team), '') IS NOT NULL
ON CONFLICT (name) DO UPDATE
SET is_active = EXCLUDED.is_active;

-- Add constraints and defaults
DO $$
BEGIN
    -- Status check constraint
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reports_status_check') THEN
        ALTER TABLE public.reports ADD CONSTRAINT reports_status_check CHECK (status in ('pending', 'ontheway', 'resolved'));
    END IF;

    -- FK to teams (only if not exists)
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reports_assigned_team_fkey') THEN
        ALTER TABLE public.reports ADD CONSTRAINT reports_assigned_team_fkey FOREIGN KEY (assigned_team) REFERENCES public.teams(name) ON UPDATE CASCADE ON DELETE SET NULL;
    END IF;
END
$$;

-- Handle queue_number sequence logic
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'reports_queue_number_seq') THEN
        CREATE SEQUENCE public.reports_queue_number_seq;
    END IF;
END
$$;

-- Set default value for queue_number if not already set
ALTER TABLE public.reports 
    ALTER COLUMN queue_number SET DEFAULT nextval('public.reports_queue_number_seq');

-- Ensure queue_number is unique
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'reports_queue_number_unique_idx') THEN
        CREATE UNIQUE INDEX reports_queue_number_unique_idx ON public.reports (queue_number);
    END IF;
END
$$;

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5. assigned_team_snapshots
-- ==========================================
CREATE TABLE IF NOT EXISTS public.assigned_team_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

ALTER TABLE public.assigned_team_snapshots
  ADD COLUMN IF NOT EXISTS report_id bigint,
  ADD COLUMN IF NOT EXISTS report_created_at timestamptz,
  ADD COLUMN IF NOT EXISTS snapshot_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS captured_at timestamptz,
  ADD COLUMN IF NOT EXISTS queue_number bigint,
  ADD COLUMN IF NOT EXISTS assigned_team text,
  ADD COLUMN IF NOT EXISTS team_name text,
  ADD COLUMN IF NOT EXISTS status text,
  ADD COLUMN IF NOT EXISTS municipality text,
  ADD COLUMN IF NOT EXISTS barangay text,
  ADD COLUMN IF NOT EXISTS location_text text,
  ADD COLUMN IF NOT EXISTS issue_type text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS latitude float8,
  ADD COLUMN IF NOT EXISTS longitude float8,
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS contact text,
  ADD COLUMN IF NOT EXISTS is_urgent boolean not null default false,
  ADD COLUMN IF NOT EXISTS resolved_at timestamptz,
  ADD COLUMN IF NOT EXISTS remarks text;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assigned_team_snapshots_report_id_fkey') THEN
        ALTER TABLE public.assigned_team_snapshots ADD CONSTRAINT assigned_team_snapshots_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS assigned_team_snapshots_report_id_idx
  ON public.assigned_team_snapshots (report_id);

CREATE INDEX IF NOT EXISTS assigned_team_snapshots_assigned_team_idx
  ON public.assigned_team_snapshots (assigned_team);

CREATE INDEX IF NOT EXISTS assigned_team_snapshots_team_name_idx
  ON public.assigned_team_snapshots (team_name);

CREATE INDEX IF NOT EXISTS assigned_team_snapshots_snapshot_at_idx
  ON public.assigned_team_snapshots (snapshot_at DESC);

WITH report_id_ranked AS (
    SELECT
        id,
        row_number() OVER (
            PARTITION BY report_id
            ORDER BY coalesce(snapshot_at, updated_at, created_at) DESC, id DESC
        ) AS rn
    FROM public.assigned_team_snapshots
    WHERE report_id IS NOT NULL
)
DELETE FROM public.assigned_team_snapshots s
USING report_id_ranked r
WHERE s.id = r.id
  AND r.rn > 1;

WITH queue_number_ranked AS (
    SELECT
        id,
        row_number() OVER (
            PARTITION BY queue_number
            ORDER BY coalesce(snapshot_at, updated_at, created_at) DESC, id DESC
        ) AS rn
    FROM public.assigned_team_snapshots
    WHERE queue_number IS NOT NULL
)
DELETE FROM public.assigned_team_snapshots s
USING queue_number_ranked q
WHERE s.id = q.id
  AND q.rn > 1;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assigned_team_snapshots_report_id_key') THEN
        ALTER TABLE public.assigned_team_snapshots ADD CONSTRAINT assigned_team_snapshots_report_id_key UNIQUE (report_id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assigned_team_snapshots_queue_number_key') THEN
        ALTER TABLE public.assigned_team_snapshots ADD CONSTRAINT assigned_team_snapshots_queue_number_key UNIQUE (queue_number);
    END IF;
END
$$;

-- Keep either legacy team field name populated.
CREATE OR REPLACE FUNCTION public.sync_assigned_team_snapshot_team_fields()
RETURNS TRIGGER AS $$
BEGIN
    IF nullif(btrim(coalesce(NEW.assigned_team, '')), '') IS NULL THEN
        NEW.assigned_team := nullif(btrim(coalesce(NEW.team_name, '')), '');
    END IF;
    IF nullif(btrim(coalesce(NEW.team_name, '')), '') IS NULL THEN
        NEW.team_name := nullif(btrim(coalesce(NEW.assigned_team, '')), '');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sync_assigned_team_snapshot_team_fields ON public.assigned_team_snapshots;
CREATE TRIGGER sync_assigned_team_snapshot_team_fields
    BEFORE INSERT OR UPDATE ON public.assigned_team_snapshots
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_assigned_team_snapshot_team_fields();

-- ==========================================
-- 6. report_images
-- ==========================================
CREATE TABLE IF NOT EXISTS public.report_images (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

ALTER TABLE public.report_images
  ADD COLUMN IF NOT EXISTS report_id bigint,
  ADD COLUMN IF NOT EXISTS image_url text;

-- FK to reports
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'report_images_report_id_fkey') THEN
        ALTER TABLE public.report_images ADD CONSTRAINT report_images_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id) ON DELETE CASCADE;
    END IF;
END
$$;

ALTER TABLE public.report_images ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 7. admin_users
-- ==========================================
CREATE TABLE IF NOT EXISTS public.admin_users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

ALTER TABLE public.admin_users
  ADD COLUMN IF NOT EXISTS username text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS password_hash text,
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS role text not null default 'staff',
  ADD COLUMN IF NOT EXISTS is_active boolean not null default true,
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz;

-- Constraints
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'admin_users_username_key') THEN
        ALTER TABLE public.admin_users ADD CONSTRAINT admin_users_username_key UNIQUE (username);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'admin_users_email_key') THEN
        ALTER TABLE public.admin_users ADD CONSTRAINT admin_users_email_key UNIQUE (email);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'admin_users_role_check') THEN
        ALTER TABLE public.admin_users ADD CONSTRAINT admin_users_role_check CHECK (role in ('admin', 'staff', 'viewer'));
    END IF;
END
$$;

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 8. notifications
-- ==========================================
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

ALTER TABLE public.notifications
  ADD COLUMN IF NOT EXISTS user_id bigint,
  ADD COLUMN IF NOT EXISTS title text,
  ADD COLUMN IF NOT EXISTS message text,
  ADD COLUMN IF NOT EXISTS is_read boolean not null default false,
  ADD COLUMN IF NOT EXISTS type text default 'info';

-- FK to customer_users
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notifications_user_id_fkey') THEN
        ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.customer_users(id) ON DELETE CASCADE;
    END IF;
END
$$;

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 9. report_status_history
-- ==========================================
CREATE TABLE IF NOT EXISTS public.report_status_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now() -- This will serve as changed_at if not provided, but we usually set it explicitly
);

ALTER TABLE public.report_status_history
  ADD COLUMN IF NOT EXISTS report_id bigint,
  ADD COLUMN IF NOT EXISTS previous_status text,
  ADD COLUMN IF NOT EXISTS new_status text,
  ADD COLUMN IF NOT EXISTS changed_by text,
  ADD COLUMN IF NOT EXISTS changed_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS remarks text;

-- FK to reports
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'report_status_history_report_id_fkey') THEN
        ALTER TABLE public.report_status_history ADD CONSTRAINT report_status_history_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id) ON DELETE CASCADE;
    END IF;
END
$$;

ALTER TABLE public.report_status_history ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 10. RPC functions
-- ==========================================

CREATE OR REPLACE FUNCTION public.set_report_status(
    p_report_id bigint,
    p_status text,
    p_team_name text DEFAULT null
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_status text := lower(btrim(coalesce(p_status, '')));
    v_team_name text := nullif(btrim(coalesce(p_team_name, '')), '');
    v_result jsonb;
BEGIN
    IF p_report_id IS NULL THEN
        RAISE EXCEPTION 'Report ID is required';
    END IF;

    IF v_status NOT IN ('pending', 'ontheway', 'resolved') THEN
        RAISE EXCEPTION 'Invalid status "%"', p_status;
    END IF;

    IF v_team_name IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM public.teams
        WHERE name = v_team_name
    ) THEN
        RAISE EXCEPTION 'Team "%" does not exist in teams table', v_team_name;
    END IF;

    UPDATE public.reports
    SET
        status = v_status,
        resolved_at = CASE WHEN v_status = 'resolved' THEN now() ELSE null END,
        assigned_team = coalesce(v_team_name, assigned_team),
        updated_at = now()
    WHERE id = p_report_id
    RETURNING to_jsonb(reports.*) INTO v_result;

    IF v_result IS NULL THEN
        RAISE EXCEPTION 'Report with ID % not found', p_report_id;
    END IF;

    RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.set_report_status(bigint, text, text) TO anon, authenticated;

-- ==========================================
-- 11. Triggers
-- ==========================================

-- Trigger for report_status_history
CREATE OR REPLACE FUNCTION public.log_report_status_change()
RETURNS TRIGGER AS $$
BEGIN
    IF (OLD.status IS DISTINCT FROM NEW.status) THEN
        INSERT INTO public.report_status_history (report_id, previous_status, new_status, changed_at)
        VALUES (NEW.id, OLD.status, NEW.status, now());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_log_report_status_change ON public.reports;
CREATE TRIGGER trigger_log_report_status_change
    AFTER UPDATE ON public.reports
    FOR EACH ROW
    EXECUTE FUNCTION public.log_report_status_change();

-- Trigger for updated_at columns
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to customer_users
DROP TRIGGER IF EXISTS set_customer_users_updated_at ON public.customer_users;
CREATE TRIGGER set_customer_users_updated_at
    BEFORE UPDATE ON public.customer_users
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply updated_at trigger to teams
DROP TRIGGER IF EXISTS set_teams_updated_at ON public.teams;
CREATE TRIGGER set_teams_updated_at
    BEFORE UPDATE ON public.teams
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply updated_at trigger to reports
DROP TRIGGER IF EXISTS set_reports_updated_at ON public.reports;
CREATE TRIGGER set_reports_updated_at
    BEFORE UPDATE ON public.reports
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply updated_at trigger to assigned_team_snapshots
DROP TRIGGER IF EXISTS set_assigned_team_snapshots_updated_at ON public.assigned_team_snapshots;
CREATE TRIGGER set_assigned_team_snapshots_updated_at
    BEFORE UPDATE ON public.assigned_team_snapshots
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

COMMIT;
